### Code
```kotlin
package com.glassthought.sandbox

import gt.sandbox.util.output.Out
import kotlinx.coroutines.delay
import kotlinx.coroutines.runBlocking
import java.util.*
import java.util.concurrent.CompletableFuture

val out = Out.standard()

fun main() = runBlocking {
  val future = CompletableFuture.supplyAsync {

    throw RuntimeException("original-exc-msg-from-supplyAsync-future-block")
    "Jon Snow"
  }

  try {
    future.get()
  } catch (e: Exception) {
    out.println("Caught exception: ${e.message}")
  }

  println("")
}

```

### Command to reproduce:
```bash
gt.sandbox.checkout.commit 7186d93f9f4e7f7d5742 \
&& cd "${GT_SANDBOX_REPO}" \
&& cmd.run.announce "./gradlew run"
```

### Recorded output of command:
```txt
> Task :app:checkKotlinGradlePluginConfigurationErrors SKIPPED
> Task :app:processResources NO-SOURCE
> Task :app:compileKotlin
> Task :app:compileJava NO-SOURCE
> Task :app:classes UP-TO-DATE

> Task :app:run
[2024-11-22T06:14:51.019728Z][elapsed-since-start:   40ms][tname:main/tid:1] Caught exception: java.lang.RuntimeException: original-exc-msg-from-supplyAsync-future-block


BUILD SUCCESSFUL in 764ms
2 actionable tasks: 2 executed
```

